version: '3.8'


services:

  db:
    image: postgres
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data
    env_file: .env_db

  app:
    build: .
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    stdin_open: true
    tty: true
    env_file:
      -.env_api 
      -.env_db



volumes:
  db:

