CREATE TABLE "sensors" (
                           "sensor_id" integer PRIMARY KEY generated by default as identity ,
                           "sensor_name" varchar(31)
);

CREATE TABLE "measurements_type" (
                                     "type_id" integer PRIMARY KEY generated by default as identity,
                                     "type_name" varchar(31),
                                     "type_units" char(4)
);

CREATE TABLE "sensors_measurements" (
                                        "sensor_id" integer,
                                        "type_id" integer,
                                        "measurment_formula" varchar(255)
);

CREATE TABLE "meteostations" (
                                 "station_id" integer PRIMARY KEY generated by default as identity,
                                 "station_name" varchar(127),
                                 "station_longitude" numeric(5,2) CHECK (station_longitude >= -180 AND station_longitude <= 180),
                                 "station_latitude" numeric(5,2) CHECK (station_latitude >= -180 AND station_latitude <= 180)
);

CREATE TABLE "meteostations_sensors" (
                                         "sensor_inventory_number" integer PRIMARY KEY generated by default as identity,
                                         "station_id" integer,
                                         "sensor_id" integer,
                                         "added_ts" timestamp default current_timestamp,
                                         "removed_ts" timestamp DEFAULT '9999-01-01'
);

CREATE TABLE "measurements" (
                                "sensor_inventory_number" integer,
                                "measurement_value" numeric(17,2),
                                "measurement_ts" timestamp default CURRENT_TIMESTAMP,
                                "measuremnet_type" integer
);

ALTER TABLE "sensors_measurements" ADD FOREIGN KEY ("sensor_id") REFERENCES "sensors" ("sensor_id");

ALTER TABLE "sensors_measurements" ADD FOREIGN KEY ("type_id") REFERENCES "measurements_type" ("type_id");

ALTER TABLE "meteostations_sensors" ADD FOREIGN KEY ("sensor_id") REFERENCES "sensors" ("sensor_id");

ALTER TABLE "meteostations_sensors" ADD FOREIGN KEY ("station_id") REFERENCES "meteostations" ("station_id");

ALTER TABLE "measurements" ADD FOREIGN KEY ("sensor_inventory_number") REFERENCES "meteostations_sensors" ("sensor_inventory_number");

ALTER TABLE "measurements" ADD FOREIGN KEY ("measuremnet_type") REFERENCES "measurements_type" ("type_id");

-- тестовые данные:
-- insert into sensors(sensor_id, sensor_name) VALUES (3, 'irina');
-- update sensors set sensor_id=?, sensor_name=? where sensor_id=?;
-- select * from  sensors_measurements join measurements_type mt on sensors_measurements.type_id = mt.type_id join measurements m on mt.type_id = m.measuremnet_type where sensor_id=1;
-- insert into measurements_type(type_id, type_name, type_units) VALUES (2, '%', 'ass');
-- insert into sensors_measurements(sensor_id, type_id, measurment_formula) VALUES (1,2,'23');
-- insert into measurements(sensor_inventory_number, measurement_value, measurement_ts, measuremnet_type) VALUES (null, 23.32, '2022.12.12', 2);